#[derive(Default)]
pub struct Satellite {
    pub name: &'static str,
    pub r_km: [f64;3],
    pub v_km_s: [f64;3],
}

// Generated by build.rs: "pub static CLIENT_SATELLITES: LazyLock<Vec<Satellite>> = ..."
include!( "../../../res/beidou.rs");