#[derive(Default)]
pub struct Satellite {
    pub name: &'static str,
    pub px: f64,
    pub py: f64,
    pub pz: f64,
    pub vx: f64,
    pub vy: f64,
    pub vz: f64,
}

// Generated by build.rs: "pub static CLIENT_SATELLITES: LazyLock<Vec<Satellite>> = ..."
include!( "../../../res/beidou.rs");